import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Custom One Piece themed fonts
const impact = localFont({
  src: "./fonts/impact.ttf",
  variable: "--font-impact",
  weight: "400",
});

const oldLondon = localFont({
  src: "./fonts/OldLondon.ttf",
  variable: "--font-old-london",
  weight: "400",
});

const canopee = localFont({
  src: "./fonts/Canopee-regular.otf",
  variable: "--font-canopee",
  weight: "400",
});

const ppEditorial = localFont({
  src: "./fonts/PPEditorialNew-Regular-BF644b214ff145f.otf",
  variable: "--font-pp-editorial",
  weight: "400",
});

const timesNewRoman = localFont({
  src: "./fonts/times-new-roman.ttf",
  variable: "--font-times-new-roman",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${impact.variable} ${oldLondon.variable} ${canopee.variable} ${ppEditorial.variable} ${timesNewRoman.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
